#!/usr/bin/env node
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { loadRegistry } from './uc-registry.mjs'

const registry = loadRegistry()
const byStatus = s => registry.use_cases.filter(uc => uc.status === s)

const section = (heading, rows) => [
  `## ${heading} — ${rows.length}`,
  '',
  '| ID | Actor | Use case | Requirement | Tier |',
  '|----|-------|----------|-------------|------|',
  ...rows.map(uc => `| ${uc.id} | ${uc.actor} | ${uc.title} | ${uc.requirement} | ${uc.tier.join(', ')} |`),
  '',
].join('\n')

const out = [
  '<!-- Generated by scripts/uc-report.mjs. Do not edit by hand. -->',
  '',
  '# Trak Use Cases',
  '',
  `Owner: ${registry.owner}`,
  '',
  'Enforced use cases block commits when they fail. Pending ones are reported',
  'but do not block. Parked ones never run.',
  '',
  'These statuses describe the test harness, not pilot readiness. Pilot scope',
  'is in [MVP Requirements](../../MVP%20Requirements); progress is in the',
  '[pilot journey index](./PILOT-INDEX.md).',
  '',
  section('Enforced', byStatus('enforced')),
  section('Pending', byStatus('pending')),
  section('Parked', byStatus('parked')),
].join('\n')

writeFileSync(resolve('docs/use-cases/README.md'), out)
console.log('docs/use-cases/README.md regenerated.')
