-- ============================================================
-- Consent threshold: 15 → 18, for both pilot markets
--
-- 20260912000001 set consent_threshold_age() to 15, reasoned entirely from
-- Greek law, for a pilot that is now UAE-first. Kostas decided 18 on
-- 2026-09-20 (#coding-agent-reviews): UAE Federal Decree-Law 26/2025 treats
-- anyone under 18 as a child, and one number that is stricter than either
-- market's floor is safer than a per-market lookup the schema cannot yet
-- express (there is still no country on the academy).
--
-- Only the body changes. Signature, IMMUTABLE, search_path, owner and ACLs
-- are preserved by CREATE OR REPLACE, so every caller — the assessment and
-- award write gates, player_consent_required(), squad_player_consent_required(),
-- 20260919120002's stale-consent report — moves with it and nothing has to
-- be re-granted.
--
-- What this changes on a live database: a linked player aged 15, 16 or 17
-- with no parental consent on record can no longer be assessed or awarded
-- until a parent grants it. That is the point. The count of such players in
-- production was read before this was written and is in the PR.
--
-- The client mirror is src/lib/consent.ts CONSENT_THRESHOLD_AGE, changed in
-- the same commit; src/__tests__/consent-threshold-agreement.test.ts reads
-- this file and fails if the two ever disagree.
--
-- Rollback: re-run the CREATE OR REPLACE from 20260912000001 (SELECT 15) in a
-- new forward migration. Do not edit this file.
-- ============================================================

CREATE OR REPLACE FUNCTION public.consent_threshold_age()
RETURNS int
LANGUAGE sql IMMUTABLE
SET search_path = public
AS $fn$
  SELECT 18;  -- Both pilot markets. UAE: under 18 is a child. Greece: stricter than the statutory 15.
$fn$;

COMMENT ON FUNCTION public.consent_threshold_age() IS
  'Parental-consent age for every pilot market (18). Change here, not at call sites; mirror in src/lib/consent.ts.';

-- Post-condition: the value a replay leaves behind, not the one this file intended.
DO $migration$
BEGIN
  IF public.consent_threshold_age() <> 18 THEN
    RAISE EXCEPTION 'consent_threshold_age() is %, expected 18', public.consent_threshold_age();
  END IF;
END;
$migration$;
