// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createPasswordRecovery } from '@/lib/password-recovery';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://xbykbqolvqyqmipikuae.supabase.co';
// TRAK-96: the new publishable key ("production"), not the legacy anon JWT,
// which stops working at the end of 2026. It is public by design, like the old one.
export const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'sb_publishable_vhCCK1tFnndJ6UBLm81YKQ_yLDZSRxt';

// Resolved values (with hardcoded fallbacks) for use anywhere that needs the
// raw URL/key — e.g. streaming edge-function fetches that can't use the client.
// Always import these instead of reading import.meta.env directly, so a build
// without the VITE_ vars injected still works.
export const SUPABASE_FUNCTIONS_URL = `${SUPABASE_URL}/functions/v1`;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Preserve this integration hook when regenerating the client. Capture before
// createClient starts consuming the URL; subscribe immediately after creation.
let recoveryCallbackUrl = window.location.href;
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

export const passwordRecovery = createPasswordRecovery(
  supabase.auth, recoveryCallbackUrl, SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY,
);
recoveryCallbackUrl = '';
